# Development profile
# Conexión directa al motor de MySQL en XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/spottrack-platform?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password


# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Developer-friendly JPA behavior (Crea las tablas automáticamente)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true


# Stripe
stripe.api-key=sk_test_51TT103GxGH6FIs40ovGKtfGMfHkKanUelSQd6EN3prtYav0e7EJK4d6J9aD2gEqHd2wejDnUjS3AC02JKAeMPL6u00zqTlojdm
# Run: stripe listen --forward-to localhost:8080/api/v1/webhooks/stripe
# Then paste the printed signing secret below
stripe.webhook-secret=whsec_ef0ffc70c99dd1a4ac57f54e986e78adc14bec39552bd2fe0de8b1efc85c0f63


# Puerto de la aplicación
server.port=8080
